-- 코드를 입력하세요
-- 출력 : 저자아이디, 저자명, 카테고리, 매출액
-- 조건 : 저자별, 카테고리별 매출액(판매량*판매가)로 구분 and 2022 01 판매데이터
-- 정렬 : 저자아이디 오름차순 카테고리 내림차순
-- 북판매 테이블이랑 북테이블 북아이디로 조인, 이후 북테이블저자아이디랑 저자테이블 아이디로 조인
-- 이후 저자별 ,북테이블 카테고리별 그룹핑
-- 매출액 계산


WITH BB AS
(SELECT B.BOOK_ID,SUM(BS.SALES*B.PRICE) AS TOTAL,B.CATEGORY,B.AUTHOR_ID
FROM BOOK_SALES AS BS JOIN BOOK AS B ON BS.BOOK_ID = B.BOOK_ID
WHERE YEAR(BS.SALES_DATE) = '2022' AND MONTH(BS.SALES_DATE) = '01'
GROUP BY BOOK_ID
ORDER BY BOOK_ID)

SELECT A.AUTHOR_ID, A.AUTHOR_NAME, BB.CATEGORY,SUM(BB.TOTAL) AS TOTAL_SALES
FROM BB JOIN AUTHOR AS A ON BB.AUTHOR_ID = A.AUTHOR_ID
GROUP BY A.AUTHOR_ID, BB.CATEGORY
ORDER BY A.AUTHOR_ID,BB.CATEGORY DESC


# SELECT B.BOOK_ID,SUM(B.BOOK_ID*B.PRICE) AS TOTAL,B.CATEGORY,B.AUTHOR_ID
# FROM BOOK_SALES AS BS JOIN BOOK AS B ON BS.BOOK_ID = B.BOOK_ID
# WHERE YEAR(BS.SALES_DATE) = '2022' AND MONTH(BS.SALES_DATE) = '01'
# GROUP BY BOOK_ID
# ORDER BY BOOK_ID
