-- 코드를 입력하세요
-- 출력 : id, 닉네임 전제주소 폰번호 (시 도로명 상세) ( 하이픈)
-- 조건 : 중고거래 게시물 등록3건이상 회원
-- 정렬 : 아이디 내림차순
SELECT UG.USER_ID,UG.NICKNAME,CONCAT(UG.CITY,' ',UG.STREET_ADDRESS1,' ',UG.STREET_ADDRESS2) AS 전체주소, CONCAT(SUBSTR(UG.TLNO,1,3),'-',SUBSTR(UG.TLNO,4,4),'-',SUBSTR(UG.TLNO,8,4)) AS '전화번호'
FROM USED_GOODS_USER AS UG JOIN USED_GOODS_BOARD AS UB ON UB.WRITER_ID = UG.USER_ID
GROUP BY UG.USER_ID
HAVING COUNT(BOARD_ID)>=3
ORDER BY UG.USER_ID DESC