-- 코드를 입력하세요

SELECT RI.REST_ID, RI.REST_NAME, RI.FOOD_TYPE,
        RI.FAVORITES AS FAVORITES, RI.ADDRESS, 
        ROUND(AVG(RR.REVIEW_SCORE),2) AS SCORE
FROM REST_REVIEW AS RR JOIN
(SELECT * 
FROM REST_INFO
WHERE ADDRESS LIKE '서울%' ) AS RI
ON RR.REST_ID = RI.REST_ID
GROUP BY RI.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC



# SELECT *
# FROM REST_REVIEW AS RR JOIN
# (SELECT REST_ID, REST_NAME, FOOD_TYPE
# FROM REST_INFO
# WHERE ADDRESS LIKE '서울%' ) AS RI
# ON RR.REST_ID = RI.REST_ID
# # GROUP BY RI.REST_ID
# ORDER BY RR.REST_ID