-- 코드를 입력하세요
-- 출력 : 년별, 월별, 성별별, 회원수
-- 조건 : 성별정보 없을시 결과제외,상품구매한 회원
-- 정렬 : 년 월 성별 오름차순
-- 온라인세일 테이블의 회원아이디
-- 그룹핑전에 성별정보없는경우를 제외해야한다. 

WITH GU AS
    (SELECT USER_ID,GENDER
    FROM USER_INFO
     WHERE GENDER IN(0,1))
     
# SELECT COUNT(GENDER) FROM GU GROUP BY GENDER
SELECT YEAR(OS.SALES_DATE) AS YEAR,MONTH(OS.SALES_DATE) AS MONTH,GU.GENDER
,COUNT(DISTINCT(GU.USER_ID)) AS USERS
FROM ONLINE_SALE AS OS JOIN GU ON OS.USER_ID = GU.USER_ID
GROUP BY YEAR(OS.SALES_DATE),MONTH(OS.SALES_DATE),GU.GENDER
ORDER BY YEAR(OS.SALES_DATE),MONTH(OS.SALES_DATE),GU.GENDER