-- 코드를 입력하세요
-- 출력 : 자동id, 평균대여기간
-- 조건 : 대여기간 7일이상인 자동차
-- 정렬 : 평균 대여기간 내림차순, 자동차아디 내림차순

# SELECT S.CAR_ID, ROUND(S.AVERAGE_DURATION,2) AS AVERAGE_DURATION
# FROM 
# (SELECT C.CAR_ID, AVG(DATEDIFF(C.END_DATE,C.START_DATE)) AS AVERAGE_DURATION
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS C
# GROUP BY C.CAR_ID) AS S
# WHERE AVERAGE_DURATION>=7
# ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC


SELECT C.CAR_ID, ROUND(AVG(DATEDIFF(C.END_DATE,C.START_DATE)+1),1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS C
GROUP BY C.CAR_ID
HAVING AVERAGE_DURATION>=7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC

