-- 코드를 입력하세요
-- 출력 : 자동차id, 대여가능 여부 AVAILABILITY
-- 조건 : 2022 10 16일에 대여중이면 대여중 대여중아니면 대여가능
-- 정확하게 startdate가 10월16일포함 이전 and enddate가 10월16일포함이후일경우 대여중
-- 그외에는 대여가능 
-- 정렬 : id기준 내림차순
# SELECT (CH2.CAR_ID) AS CAR_ID, CASE WHEN AVAL=1 THEN '대여 가능' ELSE '대여중' END AS AVAILABILITY, CH2.END_DATE
# FROM
# (SELECT CAR_ID, 
# CASE WHEN CH.CAR_ID=CH.CAR_ID THEN '1' END AS 'AVAL'
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CH
# WHERE CH.START_DATE <= '2022-10-16' AND CH.END_DATE >= '2022-10-16') AS CH1
# RIGHT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CH2 ON CH1.CAR_ID = CH2.CAR_ID
# ORDER BY CH2.CAR_ID DESC
# CASE WHEN AVAL=1 THEN '대여 가능' ELSE '대여중' END AS AVAILABILITY, CH2.END_DATE
# SELECT (CH1.CAR_ID) AS CAR_ID 
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CH1
# WHERE CH1.CAR_ID IN (SELECT CAR_ID
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CH
# WHERE CH.START_DATE <= '2022-10-16' AND CH.END_DATE >= '2022-10-16')
# GROUP BY CH1.CAR_ID
# ORDER BY CH1.CAR_ID DESC


SELECT CAR_ID, CASE WHEN max(AVAILABILITY) = '1' THEN '대여중' ELSE '대여 가능' END AS AVAILABILITY
# SELECT *
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CH 
LEFT JOIN (
    SELECT HISTORY_ID, '1' as AVAILABILITY
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CH
    WHERE CH.START_DATE <= '2022-10-16' AND CH.END_DATE >= '2022-10-16') AS CH2
        ON CH.HISTORY_ID = CH2.HISTORY_ID
GROUP BY CAR_ID
ORDER BY CAR_ID DESC
