-- 코드를 작성해주세요
-- 출력 : 분기별 대장균개체 총 수 
-- 조건 : 
-- 정렬 : 분기에 대해 오름차순

SELECT 
CASE
WHEN MONTH(E.DIFFERENTIATION_DATE) BETWEEN 0 AND 03 THEN '1Q'
WHEN MONTH(E.DIFFERENTIATION_DATE) BETWEEN 04 AND 06 THEN '2Q'
WHEN MONTH(E.DIFFERENTIATION_DATE) BETWEEN 07 AND 09 THEN '3Q'
WHEN MONTH(E.DIFFERENTIATION_DATE) BETWEEN 09 AND 12 THEN '4Q'
END AS QUARTER,
COUNT(E.ID) AS ECOLI_COUNT
FROM ECOLI_DATA AS E
GROUP BY QUARTER
