-- 코드를 입력하세요
-- 출력 : 회원 아이디 닉네임  회원별 총 거래금액
-- 조건 : 완료된 중고거래 총금액 70이상
-- 정렬 : 거래금액 오름차순
SELECT UG.USER_ID, UG.NICKNAME,SUM(UB.PRICE) AS TOTAL_SALES
from USED_GOODS_BOARD AS UB JOIN  USED_GOODS_USER AS UG ON UB.WRITER_ID = UG.USER_ID
WHERE UB.STATUS = 'DONE'
GROUP BY UB.WRITER_ID
HAVING SUM(UB.PRICE)>=700000
ORDER BY SUM(UB.PRICE)