-- 출력 : id, 형질, 부모의 형질
-- 조건 : 부모의 형질을 모두 보유 대장균
-- 정렬 : id 오름차순 

# SELECT E.ID, E.GENOTYPE,C.GENOTYPE
# FROM ECOLI_DATA AS E JOIN ECOLI_DATA AS C ON E.PARENT_ID = C.ID 
SELECT E.ID, E.GENOTYPE,C.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA AS E JOIN ECOLI_DATA AS C ON E.PARENT_ID = C.ID
WHERE E.GENOTYPE & C.GENOTYPE = C.GENOTYPE
ORDER BY E.ID