-- 출력 : id, 이름
-- 조건 : 보호시작일 보다 입양일이 더빠른 동물
-- 정렬 : 보호시작일 오름차순

SELECT AI.ANIMAL_ID, AI.NAME
FROM ANIMAL_INS AS AI JOIN ANIMAL_OUTS AS AO ON AI.ANIMAL_ID = AO.ANIMAL_ID
WHERE AI.DATETIME > AO.DATETIME
ORDER BY AI.DATETIME ASC