-- 코드를 입력하세요
-- 출력 : 월 , 자동창id, 대여횟수 records 
-- 조건 : 대여시작일 2022 08~10 데이터중 월별, id별 카운트(대여횟수 5회이상 
# -- 정렬 : 월기준 오름차순 , 자동차id 내림차순

-- 대여시작일 안 모든데이터
WITH A1 AS 
(SELECT  CAR_ID,MONTH(START_DATE) AS MONTH,HISTORY_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE YEAR(START_DATE) = '2022' AND MONTH(START_DATE) BETWEEN '08' AND '10'),
A2 AS
(SELECT CAR_ID,COUNT(HISTORY_ID)
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING COUNT(HISTORY_ID)>=5)

# SELECT *
# FROM A3;

SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(CAR_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS A
WHERE MONTH(START_DATE) BETWEEN 8 AND 10 AND
      CAR_ID IN (
          SELECT CAR_ID
          FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
          WHERE MONTH(START_DATE) BETWEEN 8 AND 10
          GROUP BY CAR_ID
          HAVING COUNT(CAR_ID) >= 5
      )
GROUP BY MONTH(START_DATE), CAR_ID
ORDER BY MONTH(START_DATE) ASC, CAR_ID DESC;

# SELECT MONTH(A.START_DATE) AS MONTH, CAR_ID,COUNT(CAR_ID) AS RECORDS
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS A
# WHERE MONTH(A.START_DATE) BETWEEN 8 AND 10 
# AND 
# A.CAR_ID IN(SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#             GROUP BY CAR_ID
#            HAVING COUNT(CAR_ID)>=5)
# GROUP BY MONTH,CAR_ID
# ORDER BY MONTH ASC,CAR_ID DESC