select  year(e1.DIFFERENTIATION_DATE) as YEAR, sum(e2.ma-e1.SIZE_OF_COLONY) as YEAR_DEV,e1.id as Id
from ECOLI_DATA as e1 join (
    select year(ed.DIFFERENTIATION_DATE) as ye, max(ed.SIZE_OF_COLONY) as ma
    from ECOLI_DATA as ed
    group by year(ed.DIFFERENTIATION_DATE)) as e2
on year(e1.DIFFERENTIATION_DATE) = e2.ye
where year(e1.DIFFERENTIATION_DATE) = e2.ye
group by e1.id, year(e1.DIFFERENTIATION_DATE)
order by year(e1.DIFFERENTIATION_DATE), YEAR_DEV

# WITH MAXS AS (
# SELECT MAX(SIZEOFCOLONY) AS MAXSIZE
# , YEAR(DIFFERENTIATIONDATE) AS YEAR
# FROM ECOLIDATA
# GROUP BY YEAR )

# SELECT M.YEAR
# , (M.MAXSIZE - E.SIZEOFCOLONY) YEARDEV
# , E.ID
# FROM MAXS M INNER JOIN ECOLIDATA E
# ON YEAR(E.DIFFERENTIATIONDATE) = M.YEAR
# WHERE YEAR(E.DIFFERENTIATIONDATE) = M.YEAR
# ORDER BY M.YEAR, YEAR_DEV