-- 코드를 작성해주세요
-- 출력 : id, 이름, 길이
-- 조건 : 종류별로 가장큰물고기만
-- 정렬 : 아이디 오름차순 정렬 
SELECT DISTINCT(FI.ID) AS ID,FN.FISH_NAME,FI.LENGTH
FROM FISH_INFO AS FI,
        FISH_NAME_INFO AS FN 
        # ON FI.FISH_TYPE = FN.FISH_TYPE 
        ,(SELECT FISH_TYPE,MAX(LENGTH) AS LENGTH FROM FISH_INFO GROUP BY FISH_TYPE) AS T 
        # ON FI.FISH_TYPE = T.FISH_TYPE
WHERE FI.FISH_TYPE = FN.FISH_TYPE AND FI.FISH_TYPE = T.FISH_TYPE AND T.LENGTH = FI.LENGTH
ORDER BY FI.ID