-- 코드를 입력하세요
-- 출력 : 성분타입, 타입당 총주문량 
-- 조건 : 상반기동안
-- 정렬 : 총주문량 오름차순

SELECT I.INGREDIENT_TYPE, SUM(F.TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF AS F JOIN ICECREAM_INFO AS I ON F.FLAVOR = I.FLAVOR
GROUP BY I.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER