-- 코드를 입력하세요
-- 출력 : 카테고리, 카테별 판매량
-- 조건 : 2022 1월 데이터
-- 정렬 : 카테고리 오름차순
SELECT B.CATEGORY, SUM(BS.SALES) AS TOTAL_SALES
FROM BOOK_SALES AS BS JOIN BOOK AS B ON BS.BOOK_ID = B.BOOK_ID
WHERE YEAR(BS.SALES_DATE) = '2022' AND MONTH(BS.SALES_DATE) = '01'
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY ASC