-- 코드를 입력하세요
-- 출력 : 상품 개수(가격대별 만원 단위)
-- 조건 : //나누기 10000해서 몫 10000으로함
SELECT S.PRICE AS PRICE_GROUP, COUNT(S.PRICE) AS PRODUCTS
FROM 
(SELECT
CASE 
WHEN P.PRICE / 10000 >=0 THEN TRUNCATE((P.PRICE / 10000),0) * 10000
END AS PRICE
FROM PRODUCT AS P) AS S
GROUP BY S.PRICE
ORDER BY S.PRICE